// <auto-generated />
using Blogp22AspNetCore.Models.Settings;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Blogp22AspNetCore.Migrations
{
    [DbContext(typeof(BlogDBContext))]
    partial class BlogDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Blogp22AspNetCore.Models.CntrEm133", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrigadaId")
                        .HasColumnType("integer");

                    b.Property<int>("IdEkg")
                        .HasColumnType("integer");

                    b.Property<long>("TimestampFromEkg")
                        .HasColumnType("bigint");

                    b.Property<long>("TimestampOnServer")
                        .HasColumnType("bigint");

                    b.Property<long>("kWArh_im")
                        .HasColumnType("bigint");

                    b.Property<long>("kWh_ex")
                        .HasColumnType("bigint");

                    b.Property<long>("kWh_im")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CNTR_EM133");
                });
#pragma warning restore 612, 618
        }
    }
}
